# Data refresh job.
#
# Fetches every externally-sourced dataset the app depends on and writes
# each one to data/cache/. Each dataset is fetched and written
# independently: if one source fails (site down, API change, network
# blip), that dataset's existing cache file is left untouched and the
# rest of the refresh continues. global.R only ever reads from
# data/cache/, so the app always has the most recent successful pull
# of each dataset, even if today's refresh partially failed.
#
# Run manually with:
#   Rscript data_refresh.R
#
# To run this once a day.
# (e.g.GitHub Actions)

library(httr)
library(jsonlite)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(sf)
library(geojsonsf)
library(rvest)
library(chromote)

source("R/data_helpers.R")

# Headless Chrome needs --no-sandbox in containerized environments, where
# chromote's automatic Docker/CI detection doesn't always add it.
chromote::set_chrome_args(unique(c(chromote::get_chrome_args(), "--no-sandbox")))

refresh_dataset <- function(name, fetch, write) {
  message("Refreshing ", name, "...")
  tryCatch(
    {
      value <- fetch()
      write(value)
      log_refresh(name, "success", n_rows = NROW(value))
      message("  OK (", NROW(value), " rows)")
      TRUE
    },
    error = function(e) {
      log_refresh(name, "failure", message = conditionMessage(e))
      message("  FAILED - keeping previous cache: ", conditionMessage(e))
      FALSE
    }
  )
}

# NET INFLOWS (scraped from okanaganwatersupply.com) -----------------------
fetch_inflow <- function() {
  url <- "https://okanaganwatersupply.com/"
  session <- read_html_live(url)
  on.exit(try(session$session$close(), silent = TRUE), add = TRUE)

  cs <- session$session

  # Locate the "Data table" tab by its link text rather than a hardcoded
  # tab id (e.g. "tab-1288-3"), since that id is generated by bslib and
  # could change if the site is redeployed.
  find_tab_js <- "
  (function() {
    var links = Array.from(document.querySelectorAll('a.nav-link'));
    var target = links.find(function(a) {
      return a.textContent.trim() === 'Data table';
    });
    return target ? target.getAttribute('href') : null;
  })();
  "
  tab_href <- cs$Runtime$evaluate(find_tab_js, returnByValue = TRUE)$result$value
  if (is.null(tab_href)) {
    stop('Could not find a nav-link with text "Data table" on the page.')
  }

  # Shiny suspends rendering of hidden-tab outputs, and a plain click on
  # the tab link doesn't reliably fire Bootstrap's shown.bs.tab event
  # inside chromote, so trigger it directly via the Bootstrap Tab API.
  show_tab_js <- sprintf("
  (function() {
    var el = document.querySelector(\"a.nav-link[href='%s']\");
    if (!el) return false;
    new bootstrap.Tab(el).show();
    return true;
  })();
  ", tab_href)
  shown <- cs$Runtime$evaluate(show_tab_js, returnByValue = TRUE)$result$value
  if (!isTRUE(shown)) {
    stop("Found the tab href but could not activate it: ", tab_href)
  }

  Sys.sleep(2) # allow Shiny to render the table

  tbl_node <- session$html_elements(paste0(tab_href, " table"))
  if (length(tbl_node) == 0) {
    stop("Data table tab was activated but no <table> was found inside it.")
  }

  html_table(tbl_node[[1]]) |>
    setNames(c("Week ending", "Current (ac-ft)", "1944-2025 avg (ac-ft)", "% of average"))
}

refresh_dataset(
  "df_inflow",
  fetch_inflow,
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_inflow.csv"))
)

# WATER CONSUMPTION (Google Sheet is manually updated but automatically refreshed) ------------------------------------------
refresh_dataset(
  "df_consumption",
  function() {
    read_csv(
      Sys.getenv("GOOGLE_SHEET_CONSUMPTION_URL"),
      show_col_types = FALSE
    )
  },
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_consumption.csv"))
)


# OKANAGAN LAKE DAILY MEAN LEVEL (weather.gc.ca API, paginated) -------------
refresh_dataset(
  "df_daily_mean",
  function() {
    limit <- 10000
    offset <- 0
    all_data <- list()
    repeat {
      url <- paste0(
        "https://api.weather.gc.ca/collections/hydrometric-daily-mean/items?",
        "f=csv",
        "&STATION_NUMBER=08NM083",
        "&datetime=1990-01-01/..",
        "&properties=IDENTIFIER,DATE,LEVEL",
        "&offset=", offset,
        "&limit=", limit
      )
      df_d <- read_csv(url, show_col_types = FALSE)
      if (nrow(df_d) == 0) break
      all_data[[length(all_data) + 1]] <- df_d
      if (nrow(df_d) < limit) break
      offset <- offset + limit
    }
    bind_rows(all_data) |>
      mutate(
        Year = year(DATE),
        Month = month(DATE),
        Day = day(DATE),
        DayOfYear = yday(DATE)
      )
  },
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_daily_mean.csv"))
)

# GROUNDWATER WELLS (BC MOE bulk export, one pull per well for the map) -----
refresh_dataset(
  "df_groundwater",
  function() {
    well_ids <- read_csv("data/well locations.csv", show_col_types = FALSE)$Well
    import_wells(well_ids)
  },
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_groundwater.csv"))
)

# DROUGHT LEVELS (ArcGIS FeatureServer, current snapshot) -------------------
refresh_dataset(
  "df_drought",
  function() {
    drought_url <- "https://services1.arcgis.com/xeMpV7tU1t4KD3Ei/arcgis/rest/services/British_Columbia_Drought_Levels_(Edit)_view/FeatureServer/27/query?f=geojson&where=(BasinName%20IN%20('Okanagan'%2C%20'South%20Thompson'%2C%20'North%20Thompson'%2C%20'Lower%20Thompson'%2C%20'Kettle%20River'%2C%20'Nicola'%2C%20'Similkameen'))&outFields=*"
    resp <- GET(drought_url)
    if (httr::http_error(resp)) {
      stop("Drought FeatureServer returned HTTP ", status_code(resp))
    }
    geojson <- content(resp, "text", encoding = "UTF-8")
    df <- geojson_sf(geojson)
    df$Date_Modified <- as.POSIXct(
      df$Date_Modified / 1000,
      origin = "1970-01-01",
      tz = "America/Vancouver"
    )
    df
  },
  function(df) atomic_write_rds(df, file.path(CACHE_DIR, "df_drought.rds"))
)

# HISTORICAL DROUGHT LEVELS (Google Sheet is manually updated but automatically refreshed) ----------------------------------
refresh_dataset(
  "df_drought_hist",
  function() {
    read_csv(
      Sys.getenv("GOOGLE_SHEET_DROUGHT_URL"),
      show_col_types = FALSE
    ) |>
      mutate(
        Start_Date = as.Date(Start_Date, format = "%Y/%m/%d %H:%M:%S%z"),
        DroughtLevel = case_when(
          DroughtLevel == "Not updated outside of core drought season" ~ 6,
          TRUE ~ as.numeric(DroughtLevel)
        )
      ) |>
      select(BasinName, Start_Date, DroughtLevel) |>
      arrange(BasinName, Start_Date)
  },
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_drought_hist.csv"))
)

# STREAM THERMAL STATE (daily zip download) ---------------------------------
refresh_dataset(
  "df_stream_temp",
  function() {
    tmp_zip <- tempfile(fileext = ".zip")
    tmp_dir <- tempfile()
    dir.create(tmp_dir)
    on.exit(unlink(c(tmp_zip, tmp_dir), recursive = TRUE), add = TRUE)

    download.file(
      "https://storage.googleapis.com/obwb-okanagan-streamtemp/oktemp_streamtemp_latest.zip",
      destfile = tmp_zip,
      quiet = TRUE,
      mode = "wb"
    )
    unzip(zipfile = tmp_zip, exdir = tmp_dir)
    read.csv(file.path(tmp_dir, "stream_temperature_daily.csv"))
  },
  function(df) atomic_write_csv(df, file.path(CACHE_DIR, "df_stream_temp.csv"))
)

message("Data refresh complete. See ", file.path(CACHE_DIR, "refresh_log.csv"), " for a run history.")
